name: Regression Test
'on':
  push:
    branches:
      - main

jobs:
  execution:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node Env
        uses: actions/checkout@v5
      - name: Execute Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_MAILOSAUR_API_KEY: ${{secrets.CYPRESS_MAILOSAUR_API_KEY}}